### ISSUE TITLE
root or sudo

### ISSUE THREAD

**Issue by laoshaw** [myplaceonline/posixcube#12]
normally ssh disallows ssh access, can the script support sudo by default?

**Comment by laoshaw** [comment]
https://github.com/laoshaw/posixcube has my hack for sudo and non-standard-ssh-port, feel free to pull if needed.

**Comment by kevgrig** [comment]
Ahh yes, `sudo` isn't something I've dealt with yet. Interestingly, it doesn't seem that `sudo` is part of the POSIX standard. I'll need to think about this a bit...

**Comment by kevgrig** [comment]
Relevant: http://unix.stackexchange.com/a/48553

**Comment by kevgrig** [comment]
Commit 4281406 should fix this issue. Basically, the new `-S` option will run the `cube_package` and `cube_service` commands with sudo. More details in the Philosophy section:

> 3. Recent versions of many distributions encourage running most commands
   as a non-superuser, and then using `sudo` if needed, with some distributions
   disallowing remote SSH using the `root` account by default. First, the `sudo`
   command is not standardized (see http://unix.stackexchange.com/a/48553).
   Moreoever, it is not enough to prefix posixcube APIs with `sudo` because
   `sudo` doesn't pass along functions (even if they're exported and `sudo` is
   executed with --preserve-env). `su -c` may be used but it requires
   password input. For the most common use case of requiring `sudo` for
   cube_package and cube_service, if `-S` is specified, the commands within
   those APIs are executed using `sudo`. If you need to run something else as a
   superuser and you need access to the posixcube APIs, see the `cube_sudo` API.

If this is resolved for you, please close this issue.

**Comment by laoshaw** [comment]
Thanks!

**Comment by aero** [comment]
Hi

I tested posixcube with "./posixcube.sh -d -S -h myhost -c test.sh" command.
but I've got the following error message.
```
.
.
Usage: /etc/init.d/atop {start|stop|status|restart|force-reload}
[Sat Jul 15 22:34:15 KST 2017] [myhost test.sh:9] Error: Previous command failed with code 1
[Sat Jul 15 22:34:15 KST 2017] [myhost test.sh:9] Error: Stack:
.
.
```
it's from test.sh line 9.
```
cube_service enable atop
```
I am using Ubuntu 14.04 LTS

posixcube.sh finally execute "cube_service enable atop" as "servce atop enable" on my Ubuntu.
```
root@myhost:~# service atop enable
Usage: /etc/init.d/atop {start|stop|status|restart|force-reload}
```
It's incompatible with Ubuntu's service command.

I've found several command line options incompitablities within short test.
another https://github.com/myplaceonline/posixcube/issues/18

I think posixcube should be tested on various linux distributions and versions.

**Comment by kevgrig** [comment]
@aero Thanks for the report. I've [updated](https://github.com/myplaceonline/posixcube/blob/64fcc1d182599be6fa257a72d94adf12affeb374/posixcube.sh#L917) cube_service to use `chkconfig` and `update-rc.d` on older versions of Fedora- and Debian-based distributions for cube_service `enable` and `disable`.

I agree posixcube needs more testing on more operating systems. I've updated the [testing issue](https://github.com/myplaceonline/posixcube/issues/16#issuecomment-315551529) with that note.
