### ISSUE TITLE
"-s  Skip remote host initialization" option works as document ?

### ISSUE THREAD

**Issue by aero** [myplaceonline/posixcube#20]
Hi
```
-s        Skip remote host initialization (making ~/posixcubes, uploading
            posixcube.sh, etc.)
```
I tried like the following.
```
$ ./posixcube.sh -h myhost -s uptime
[2017. 07. 19. (수) 20:43:49 KST] Preparing hosts: myhost ...
[2017. 07. 19. (수) 20:43:49 KST] Completed preparation.
[2017. 07. 19. (수) 20:43:49 KST] Transferring files to hosts: myhost ...
[2017. 07. 19. (수) 20:43:50 KST] Completed transfers.
[2017. 07. 19. (수) 20:43:50 KST] [myhost] Executing on myhost ...
/home/aero/posixcubes/./cube_exec.sh: line 4: /home/aero/posixcubes/posixcube.sh: No such file or directory
Could not source ~/posixcubes/posixcube.sh script
[2017. 07. 19. (수) 20:43:51 KST] [myhost] Remote commands through SSH failed with return code 1
$
```
I got some error message. 
and posixcube directory was created on server side.
```
$ ls -la ~/posixcubes/
total 12
drwxrwxr-x  2 aero aero 4096 Jul 19 20:43 .
drwxr-xr-x 42 aero aero 4096 Jul 19 20:43 ..
-rwxr-xr-x  1 aero aero  438 Jul 19 20:43 cube_exec.sh
```

**Comment by kevgrig** [comment]
Hi, sorry for the delay. Busy weekend.

The purpose of `-s` was to avoid uploading cubes, posixcube.sh itself, and envar files in the case that the user knows that none of those have changed. In effect, it's assuming that all of those files have been uploaded previously (to save the `rsync`s). I'm guessing you got that error because `posixcube.sh` hadn't yet been run without `-s` on that host?

Some of the log statements (e.g. `Preparing hosts [...]`, `Transferring files to hosts [...]`, etc.) are incorrect as those should be inside the `if` that checks that `-s` is not set. However, the deeper issue is that this feature is essentially broken when using encrypted envar files because those are deleted (for obvious security reasons) at the end of the execution. I could change `-s` to skip uploading everything except decrypted envar files; however, that kind of defeats the purpose because the majority of the overhead of the `rsync`s are just the setup and teardown. So I think I will just comment out this feature unless you'd like it for the non-encrypted-envar case.

**Comment by aero** [comment]
I see.

I have another question.
Why does posixcube use rsync for file transfering instead of scp(comes along with ssh package) ?

**Comment by kevgrig** [comment]
`rsync` is used to avoid transferring files that haven't been updated. In [my use case](https://github.com/myplaceonline/myplaceonline_posixcubes), all cubes and templates are about 1.3MB. However, I agree that it can be annoying to require installing `rsync` on Debian just for posixcube. Do you think it would be better to default to `scp` and then have `rsync` as an option?

**Comment by aero** [comment]
Task like deploying tarball or template file needs to transfer files.
but I think it is nearly one time job and is rarely expected to reuse the same file at common case.
So rsync is not much help.
and I like ssh option like "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" for bypass annoying confirming prompt.
but rsync in posixcube doesn't respect those options.
```
$ ./posixcube.sh -o ConnectionAttempts=1 -o ConnectTimeout=3 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -u aero -h myhost uptime

[2017. 07. 27. (목) 23:05:57 KST] Preparing hosts: myhost ...
Warning: Permanently added 'myhost (ECDSA) to the list of known hosts.
[2017. 07. 27. (목) 23:05:57 KST] Completed preparation.
[2017. 07. 27. (목) 23:05:57 KST] Transferring files to hosts: myhost ...
The authenticity of host 'myhost  can't be established.
ECDSA key fingerprint is SHA256:.......
Are you sure you want to continue connecting (yes/no)?
```
see https://stackoverflow.com/a/11829094

Task like simple remote command execution or task don't need to transfer file. but posixcube seems to send some bootstrap files. but it is not too large to transfer. 

I think that posixcube is remote deploying or configuration tool.
Transferring files task is expected to take comparably less times than remote task. 

If I need to execute simple remote command on many remote server, I will use vanilla ssh with parallel tool like clusterssh , parallal or own for loop.. etc.

**Comment by kevgrig** [comment]
The latest commit changes the default to `scp` and adds a `-R` option to use `rsync`. For the `scp` and `rsync` ssh `-o` options, do you want to use the same `-o` options used for posixcube's `ssh` commands, or do you want a separate option?

**Comment by aero** [comment]
Thank you.
I prefer the same thing.

**Comment by kevgrig** [comment]
Please try the latest commit. Any `-o` options are now passed to `scp` or `rsync` (with `-e ssh`).

**Comment by aero** [comment]
Works well.
Thank you.
